### ISSUE TITLE
Homely as an Intranet + Help for a fellow entrepreneur

### ISSUE THREAD

**Issue by akevascientific** [Terrance/Homely#26]
Hi,
I have been using Homely for a couple of months and am liking it. I hit the max number of 10 shortcuts on the Google Chrome starting page so that is when I started searching around for an extension that could overcome this.

I even think your extension could work as a pseudo-intranet (that's the Suggestion bit of this message), and I intend to set up the first prototype of an "intranet" for my startup using Homely.

The Help for a fellow entrepreneur has to do with how I found Homely. As I said, I searched on Google and found a page, I believe it was a forum, where you laid out a few options for a person with a similar question as mine. At the end, I believe, you cited Homely and its features. Then you said something like "Disclaimer: I am the developer of Homely". Do you remember where you wrote this and what those two other (competitor) solutions were?

My startup has a relationship with a Business School and I am thinking of tasking them (undergraduate students) to map out how companies do this type of approach (a "comparison" or "round-up" of products involving even competitor products) where, despite outright giving options to not go with your solution, you end up going with it (I'm an example going for Homely).

I've seen this appraoch with other software too. Does this marketing approach have a name?!

Thanks a bunch in advance.
My e-mail: ak@evascientific.com

**Comment by Terrance** [comment]
> you laid out a few options for a person with a similar question as mine

[This Reddit comment](https://www.reddit.com/r/chrome/comments/261cc7/speed_dial_2_alternatives/chmpqi5/)?

It wasn't really intended to be marketing, and I am no entrepreneur so I'm not sure what advice I can give you.  Ultimately the new tab market was/is pretty saturated, and it's very much personal taste, which is why I ended up making my own as none of the existing options fitted what I wanted.  These days I've moved on and Homely doesn't really fit for me any more either -- I just use the Firefox stock new tab page and rely more on address bar autocomplete to get to most places.
